import Head from 'next/head';
import Carousel from '../components/carousel/Carousel';
import MoviesHome from '../components/movies/MoviesHome';
import { API_KEY } from '../utils/util';

export default function Home({
  popularMovies, 
  topRatedMovies,
  actionMovies,
  animationMovies,
  comedyMovies,
  familyMovies,
  fantasyMovies,
  romanceMovies
}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel movies={popularMovies} />
      <div className='container'>
      <MoviesHome movies={popularMovies} title="Popular Movies" />
      <MoviesHome movies={topRatedMovies} title="Top Rated Movies"/>
      <MoviesHome movies={actionMovies} title="Action"/>
      <MoviesHome movies={animationMovies} title="Animation"/>
      <MoviesHome movies={comedyMovies} title="Comedy"/>
      <MoviesHome movies={familyMovies} title="Family"/>
      <MoviesHome movies={fantasyMovies} title="Fantasy"/>
      <MoviesHome movies={romanceMovies} title="Romance"/>
      </div>
      
    </div>
  )
}


export async function getServerSideProps(context) {

  const base_url = process.env.BASE_URL
  const discover_movie_url = process.env.DISCOVER_MOVIE_URL

  const [
    popularMoviesRes,
    topRatedMoviesRes,
    actionMoviesRes,
    animationMoviesRes,
    comedyMoviesRes,
    familyMoviesRes,
    fantasyMoviesRes,
    romanceMoviesRes] = await Promise.all([
    fetch(
      `${base_url}movie/popular?api_key=${API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `${base_url}movie/top_rated?api_key=${API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `${base_url}discover/movie?api_key=${API_KEY}&sort_by=popularity.desc&page=1&with_genres=28&with_watch_monetization_types=flatrate`
    ),
    fetch(
      `${base_url}discover/movie?api_key=${API_KEY}&sort_by=popularity.desc&page=1&with_genres=16&with_watch_monetization_types=flatrate`
    ),
    fetch(
      `${base_url}discover/movie?api_key=${API_KEY}&sort_by=popularity.desc&page=1&with_genres=35&with_watch_monetization_types=flatrate`
    ),
    fetch(
      `${base_url}discover/movie?api_key=${API_KEY}&sort_by=popularity.desc&page=1&with_genres=10751&with_watch_monetization_types=flatrate`
    ),
    fetch(
      `${base_url}discover/movie?api_key=${API_KEY}&sort_by=popularity.desc&page=1&with_genres=14&with_watch_monetization_types=flatrate`
    ),
    fetch(
      `${base_url}discover/movie?api_key=${API_KEY}&sort_by=popularity.desc&page=1&with_genres=10749&with_watch_monetization_types=flatrate`
    ),
  ])

  const [
    popularMovies, 
    topRatedMovies,
    actionMovies,
    animationMovies,
    comedyMovies,
    familyMovies,
    fantasyMovies,
    romanceMovies] = await Promise.all([
      popularMoviesRes.json(),
      topRatedMoviesRes.json(),
      actionMoviesRes.json(),
      animationMoviesRes.json(),
      comedyMoviesRes.json(),
      familyMoviesRes.json(),
      fantasyMoviesRes.json(),
      romanceMoviesRes.json(),
    ]);

  return {
    props: {
      popularMovies: popularMovies.results,
      topRatedMovies: topRatedMovies.results,
      actionMovies: actionMovies.results,
      animationMovies: animationMovies.results,
      comedyMovies: comedyMovies.results,
      familyMovies: familyMovies.results,
      fantasyMovies: fantasyMovies.results,
      romanceMovies: romanceMovies.results,
    }
  }
}